"""MRM Assembler — ghép nhiều module thành báo cáo hoàn chỉnh."""

from __future__ import annotations

import os
from datetime import datetime
from typing import List

from .validator import MRMValidator


def assemble_report(input_dir: str, output_path: str, include_toc: bool = True) -> None:
    """Ghép nhiều module MRM thành một báo cáo Markdown duy nhất.

    Chỉ các file đã qua ``validate_directory`` mới được đưa vào báo cáo.
    File ``index.md`` bị loại trừ.

    Args:
        input_dir: Thư mục chứa các module MRM.
        output_path: Đường dẫn file báo cáo đầu ra.
        include_toc: Có sinh mục lục (Table of Contents) ở đầu hay không.
    """
    validator = MRMValidator(verbose=False)
    results = validator.validate_directory(input_dir)

    file_contents: List[dict] = []
    for result in sorted(results, key=lambda r: r.file_path):
        if "index.md" in result.file_path:
            continue

        # Dùng frontmatter đã cache — không đọc file lần 2
        fm = result.frontmatter
        if fm is None:
            print(f"⚠️  Bỏ qua file không có frontmatter: {result.file_path}")
            continue

        try:
            with open(result.file_path, "r", encoding="utf-8") as fh:
                content = fh.read()
            _, body = validator.extract_frontmatter(content)
            file_contents.append(
                {
                    "title": str(fm.get("title", "Untitled")),
                    "id": str(fm.get("id", "")),
                    "body": body,
                    "path": result.file_path,
                }
            )
        except Exception as exc:
            print(f"⚠️  Bỏ qua file {result.file_path}: {exc}")

    report = (
        f'---\n'
        f'title: "Báo cáo Nghiên cứu Hoàn chỉnh"\n'
        f'author: "MRM Auto-Assembler"\n'
        f'date: "{datetime.now().strftime("%Y-%m-%d")}"\n'
        f'tags: [report, assembled]\n'
        f'---\n\n'
        f'# Báo cáo Nghiên cứu Hoàn chỉnh\n\n'
        f'> **Generated by MRM Toolkit** |'
        f' {len(file_contents)} modules |'
        f' {datetime.now().strftime("%Y-%m-%d %H:%M")}\n\n'
    )

    if include_toc:
        report += "## Mục lục\n\n"
        for i, fc in enumerate(file_contents, 1):
            safe_title = fc["title"].replace(" ", "-").lower()
            report += f"{i}. [{fc['title']}](#{safe_title})\n"
        report += "\n---\n\n"

    for fc in file_contents:
        report += f"\n## {fc['title']}\n"
        if fc["id"]:
            report += f"*File ID: `{fc['id']}`*\n"
        report += fc["body"]
        report += "\n---\n"

    with open(output_path, "w", encoding="utf-8") as fh:
        fh.write(report)

    print(f"✅ Đã ghép báo cáo: {output_path} ({len(file_contents)} modules)")
